### ISSUE TITLE
VALIDATE_ALL_CODEBASE: false requires access to the repo? "The requested URL returned error: 400"

### ISSUE THREAD

**Issue by bengeset96** [oxsecurity/megalinter#1718]
Hello project contributors and maintainers!

I am trying to utilize `VALIDATE_ALL_CODEBASE: false` since MegaLinter is used on pull requests and there is no need of linting files that is not related to the pull request in this case.

After configuration, the CI starts throwing out the following error:

```
2022-08-08T06:53:09.9889020Z 
2022-08-08T06:53:09.9889371Z MegaLinter now collects the files to analyse
2022-08-08T06:53:09.9889817Z Listing updated files in [/tmp/lint] using git diff.
2022-08-08T06:53:10.0904397Z Traceback (most recent call last):
2022-08-08T06:53:10.0905135Z   File "/usr/local/lib/python3.10/runpy.py", line 196, in _run_module_as_main
2022-08-08T06:53:10.0905881Z     return _run_code(code, main_globals, None,
2022-08-08T06:53:10.0906361Z   File "/usr/local/lib/python3.10/runpy.py", line 86, in _run_code
2022-08-08T06:53:10.0906803Z     exec(code, run_globals)
2022-08-08T06:53:10.0907401Z   File "/megalinter/run.py", line 15, in <module>
2022-08-08T06:53:10.0907762Z     linter.run()
2022-08-08T06:53:10.0908149Z   File "/megalinter/MegaLinter.py", line 142, in run
2022-08-08T06:53:10.0908550Z     self.collect_files()
2022-08-08T06:53:10.0908962Z   File "/megalinter/MegaLinter.py", line 506, in collect_files
2022-08-08T06:53:10.0909520Z     all_files = self.list_files_git_diff()
2022-08-08T06:53:10.0909964Z   File "/megalinter/MegaLinter.py", line 617, in list_files_git_diff
2022-08-08T06:53:10.0910433Z     repo.git.fetch("origin", f"{remote_ref}:{local_ref}")
2022-08-08T06:53:10.0911741Z   File "/usr/local/lib/python3.10/site-packages/git/cmd.py", line 639, in <lambda>
2022-08-08T06:53:10.0917022Z     return lambda *args, **kwargs: self._call_process(name, *args, **kwargs)
2022-08-08T06:53:10.0918061Z   File "/usr/local/lib/python3.10/site-packages/git/cmd.py", line 1184, in _call_process
2022-08-08T06:53:10.0925746Z     return self.execute(call, **exec_kwargs)
2022-08-08T06:53:10.0926560Z   File "/usr/local/lib/python3.10/site-packages/git/cmd.py", line 984, in execute
2022-08-08T06:53:10.0934159Z     raise GitCommandError(redacted_command, status, stderr_value, stdout_value)
2022-08-08T06:53:10.0935020Z git.exc.GitCommandError: Cmd('git') failed due to: exit code(128)
2022-08-08T06:53:10.0935771Z   cmdline: git fetch origin HEAD:refs/remotes/origin/HEAD
2022-08-08T06:53:10.0936686Z   stderr: 'fatal: unable to access 'https://myorg.visualstudio.com/myproject/_git/myrepo/': The requested URL returned error: 400'
2022-08-08T06:53:10.4249718Z ##[error]Bash exited with code '1'.
2022-08-08T06:53:10.4326155Z ##[section]Finishing: Validate non-module files with MegaLinter
```
`VALIDATE_ALL_CODEBASE: true` works fine.

What kind of permissions must be given to MegaLinter? I am struggling to find some documentation around the topic. I taught MegaLinter were able to run a normal git diff locally when checking out the repo.

**Comment by Kurt-von-Laven** [comment]
MegaLinter can only diff against your default branch if it is present. As a last resort, we attempt to fetch the default branch, which fails if we don't have access to your repository. In GitHub Actions, the solution is to clone with `fetch-depth: 0` (meaning a full checkout) since clones are shallow by default.

**Comment by bengeset96** [comment]
@Kurt-von-Laven 

Based on the configuration documentation it seems like the default branch value is `HEAD`, which in AzureDevops defaults to `main`.

Already running the checkout with `fetchDepth: 0` so should have the full timeline.

I have to identify what makes MegaLinter to not respect the local HEAD^ and HEAD as first priority. 

`
 2022-08-08T06:53:10.0935771Z   cmdline: git fetch origin HEAD:refs/remotes/origin/HEAD`

I'll try to explicit set the main branch as default in the configuration file.

**Comment by Kurt-von-Laven** [comment]
We diff against `origin/HEAD` as opposed to the local `HEAD` (since that would guarantee an empty diff) unless `DEFAULT_BRANCH` is specified. You can run `git branch --remotes` to see whether `origin/HEAD` is present. Apologies that I don't know more about Azure DevOps.

**Comment by bengeset96** [comment]
I understand, `origin/HEAD` is available when doing checkout in Azure DevOps, but it might be related to some certain permissions that must be given.

I ended up just using `DEFAULT_BRANCH: main` and that did the trick. Seems like this works as `git diff HEAD^ HEAD`, so I will utilize that.

**Comment by Kurt-von-Laven** [comment]
Glad it's working. In case this helps others in the future, there aren't relevant permissions within local git clones as I understand it. Permissions are only relevant here when fetching (or pulling or cloning). When you specify `DEFAULT_BRANCH: main`, MegaLinter is doing (in essence) `git diff origin/main`. `HEAD^` never enters into the matter. The distinction is potentially irrelevant if all of your pull requests contain exactly 1 commit (implying they are never rebased on any branch other than `main`). Just don't want folks to get thrown off if that assumption doesn't hold for them.
