### ISSUE TITLE
markdown-link-check error

### ISSUE THREAD

**Issue by schorlton** [oxsecurity/megalinter#1723]
Running
```bash
docker run --rm -v "$PWD":/tmp/lint \ 
        -e "VALIDATE_ALL_CODEBASE=false" \
        -e "APPLY_FIXES=all" \
        oxsecurity/megalinter-documentation:v6.3.0
```
on a repo. Getting a weird error...not sure what's going on. Thanks for your help!!

```bash
Results of markdown-link-check linter (version 3.10.2)
See documentation on https://oxsecurity.github.io/megalinter/latest/descriptors/markdown_markdown_link_check/
-----------------------------------------------

❌ [ERROR] for workspace /tmp/lint
Linter raw log:
node:fs:1552
  handleErrorFromBinding(ctx);
  ^

Error: ENOENT: no such file or directory, stat '5'
    at Object.statSync (node:fs:1552:3)
    at Command.<anonymous> (/node-deps/node_modules/markdown-link-check/markdown-link-check:85:38)
    at Command.listener [as _actionHandler] (/node-deps/node_modules/markdown-link-check/node_modules/commander/index.js:426:31)
    at Command._parseCommand (/node-deps/node_modules/markdown-link-check/node_modules/commander/index.js:1002:14)
    at Command.parse (/node-deps/node_modules/markdown-link-check/node_modules/commander/index.js:801:10)
    at getInputs (/node-deps/node_modules/markdown-link-check/markdown-link-check:97:7)
    at main (/node-deps/node_modules/markdown-link-check/markdown-link-check:215:20)
    at Object.<anonymous> (/node-deps/node_modules/markdown-link-check/markdown-link-check:229:1)
    at Module._compile (node:internal/modules/cjs/loader:1099:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10) {
  errno: -2,
  syscall: 'stat',
  code: 'ENOENT',
  path: '5'
}

Node.js v17.9.0

```

EDIT: Just realized I also have `MARKDOWN_MARKDOWN_LINK_CHECK_ARGUMENTS: "--retry 5"` in my `.mega-linter.yaml`....could this be triggering it?

**Comment by Kurt-von-Laven** [comment]
Have you already attempted to reproduce the issue by running markdown-link-check directly?

**Comment by nvuillam** [comment]
@schorlton if you add `LOG_LEVEL: DEBUG` in your config, you'll see the exact call made by markdown-links-check

You can also try the following;

`MARKDOWN_MARKDOWN_LINK_CHECK_ARGUMENTS: ["--retry","5"]`

**Comment by schorlton** [comment]
Thank you both for your smart suggestions! @Kurt-von-Laven was correct that this is a markdown-link-check bug (sorry for reporting here) so I will close the issue.

Interestingly, I also noticed that Megalinter already has 5 retries set by default in Megalinter, so I can go ahead and remove this config. Thanks again!

**Comment by nvuillam** [comment]
Glad your issue is solved :)
