### ISSUE TITLE
Error's missing

### ISSUE THREAD

**Issue by react-universe** [oxsecurity/megalinter#1940]
When I run Mega linter locally for Identify Errors in java file Then I got this output

`Linter raw log:
Starting audit...
com.puppycrawl.tools.checkstyle.api.CheckstyleException: Exception was thrown while processing /tmp/lint/main.java
    at com.puppycrawl.tools.checkstyle.Checker.processFiles(Checker.java:307)
    at com.puppycrawl.tools.checkstyle.Checker.process(Checker.java:224)
    at com.puppycrawl.tools.checkstyle.Main.runCheckstyle(Main.java:416)
    at com.puppycrawl.tools.checkstyle.Main.runCli(Main.java:339)
    at com.puppycrawl.tools.checkstyle.Main.execute(Main.java:196)
    at com.puppycrawl.tools.checkstyle.Main.main(Main.java:131)
Caused by: com.puppycrawl.tools.checkstyle.api.CheckstyleException: IllegalStateException occurred while parsing file /tmp/lint/main.java.
    at com.puppycrawl.tools.checkstyle.JavaParser.parse(JavaParser.java:105)
    at com.puppycrawl.tools.checkstyle.TreeWalker.processFiltered(TreeWalker.java:153)
    at com.puppycrawl.tools.checkstyle.api.AbstractFileSetCheck.process(AbstractFileSetCheck.java:98)
    at com.puppycrawl.tools.checkstyle.Checker.processFile(Checker.java:335)
    at com.puppycrawl.tools.checkstyle.Checker.processFiles(Checker.java:294)
    ... 5 more
Caused by: java.lang.IllegalStateException: 7:11: no viable alternative at input 'vod'
    at com.puppycrawl.tools.checkstyle.JavaParser$CheckstyleErrorListener.syntaxError(JavaParser.java:255)
    at org.antlr.v4.runtime.ProxyErrorListener.syntaxError(ProxyErrorListener.java:41)
    at org.antlr.v4.runtime.Parser.notifyErrorListeners(Parser.java:544)
    at org.antlr.v4.runtime.DefaultErrorStrategy.reportNoViableAlternative(DefaultErrorStrategy.java:310)
    at org.antlr.v4.runtime.DefaultErrorStrategy.reportError(DefaultErrorStrategy.java:136)
    at com.puppycrawl.tools.checkstyle.grammar.java.JavaLanguageParser.typeDeclaration(JavaLanguageParser.java:700)
    at com.puppycrawl.tools.checkstyle.grammar.java.JavaLanguageParser.compilationUnit(JavaLanguageParser.java:412)
    at com.puppycrawl.tools.checkstyle.JavaParser.parse(JavaParser.java:99)
    ... 9 more
Caused by: org.antlr.v4.runtime.NoViableAltException
    at org.antlr.v4.runtime.atn.ParserATNSimulator.noViableAlt(ParserATNSimulator.java:2031)
    at org.antlr.v4.runtime.atn.ParserATNSimulator.execATN(ParserATNSimulator.java:470)
    at org.antlr.v4.runtime.atn.ParserATNSimulator.adaptivePredict(ParserATNSimulator.java:396)
    at com.puppycrawl.tools.checkstyle.grammar.java.JavaLanguageParser.typeDeclaration(JavaLanguageParser.java:662)
    ... 11 more
Checkstyle ends with 1 errors.
`
My expectation was All of these errors in below image should be mentioned in the above errors.
![first](https://user-images.githubusercontent.com/113578023/194319753-92593d7e-0e80-4d74-a402-c1cf5ba224e4.png)

so is there any other way to get this Error List ?

**Comment by nvuillam** [comment]
I think that checkstyle needs to be able to parse the java sources to be able to lint them

If this is an unexpected behaviour in your opinion, you can notify them on their repo :) https://github.com/checkstyle/checkstyle
