### ISSUE TITLE
Megalinter fails with some python error

### ISSUE THREAD

**Issue by KnisterPeter** [oxsecurity/megalinter#1955]
**Describe the bug**
Using megalinter on our repo does lead to a failing `jscpd`.
We haven't setup and configuration, just plain megalinter.

**To Reproduce**
It's a private repo and I haven't yet understood was is going on.

**Expected behavior**
`jscdp` should be able to run or being disabled.

**Additional context**

Log Output:
```shell
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/usr/local/lib/python3.10/site-packages/megalinter-0.1-py3.10.egg/megalinter/MegaLinter.py", line 37, in run_linters
    linter.run()
  File "/usr/local/lib/python3.10/site-packages/megalinter-0.1-py3.10.egg/megalinter/Linter.py", line 667, in run
    return_code, stdout = self.process_linter()
  File "/usr/local/lib/python3.10/site-packages/megalinter-0.1-py3.10.egg/megalinter/Linter.py", line 804, in process_linter
    return_code, return_output = self.execute_lint_command(command)
  File "/usr/local/lib/python3.10/site-packages/megalinter-0.1-py3.10.egg/megalinter/Linter.py", line 846, in execute_lint_command
    process = subprocess.run(
  File "/usr/local/lib/python3.10/subprocess.py", line 501, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/usr/local/lib/python3.10/subprocess.py", line 966, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/local/lib/python3.10/subprocess.py", line 1842, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'jscpd'
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.10/site-packages/megalinter-0.1-py3.10.egg/megalinter/run.py", line 15, in <module>
    linter.run()
  File "/usr/local/lib/python3.10/site-packages/megalinter-0.1-py3.10.egg/megalinter/MegaLinter.py", line 166, in run
    self.process_linters_parallel(active_linters, linters_do_fixes)
  File "/usr/local/lib/python3.10/site-packages/megalinter-0.1-py3.10.egg/megalinter/MegaLinter.py", line 267, in process_linters_parallel
    updated_linters = pool_result.get()
  File "/usr/local/lib/python3.10/multiprocessing/pool.py", line 771, in get
    raise self._value
FileNotFoundError: [Errno 2] No such file or directory: 'jscpd'
```

**Comment by Kurt-von-Laven** [comment]
Are you able to reproduce the error by running jscpd directly? You can add `DISABLE_LINTERS: COPYPASTE_JSCPD` to your MegaLinter config file as a temporary workaround. What flavor and version of MegaLinter are you using? I ask because jscpd works for us at MegaLinter v6.12.0. I did notice that the [documentation](https://oxsecurity.github.io/megalinter/6.12.0/descriptors/copypaste_jscpd/) incorrectly states that MegaLinter is at jscpd 3.3.26. In reality, I suspect it is at the latest version: 3.5.0.

**Comment by KnisterPeter** [comment]
Thanks @Kurt-von-Laven. I'll give it a try.

**Comment by KnisterPeter** [comment]
Hmm, this `npx jscpd --pattern 'src/**/*.ts'` does work on our codebase.
It seems to be a problem with megalinter.

**Comment by nvuillam** [comment]
https://github.com/oxsecurity/megalinter/blob/f58627dfe556c4a85e53417f9b73ac505114d93b/megalinter/descriptors/copypaste.megalinter-descriptor.yml#L60

jscpd is downgraded in ML, probably because there has been a new version that was crashing

**Comment by KnisterPeter** [comment]
Both version run fine locally.

**Comment by KnisterPeter** [comment]
After disabling jscpd, I'll get this one:

```
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.10/site-packages/megalinter-0.1-py3.10.egg/megalinter/run.py", line 15, in <module>
    linter.run()
  File "/usr/local/lib/python3.10/site-packages/megalinter-0.1-py3.10.egg/megalinter/MegaLinter.py", line 166, in run
    self.process_linters_parallel(active_linters, linters_do_fixes)
  File "/usr/local/lib/python3.10/site-packages/megalinter-0.1-py3.10.egg/megalinter/MegaLinter.py", line 267, in process_linters_parallel
    updated_linters = pool_result.get()
  File "/usr/local/lib/python3.10/multiprocessing/pool.py", line 771, in get
    raise self._value
FileNotFoundError: [Errno 2] No such file or directory: 'v8r'
  ❌  Failure - Main markus-wolf/oxsecurity-megalinter@v6
exit with `FAILURE`: 1
```

As this is running inside the docker container of megalinter, how can I debug this?

**Comment by nvuillam** [comment]
What MegaLinter version are you using ? v8r is supposed to be present in all of them

**Comment by KnisterPeter** [comment]
I'm using it in github actions like this:
```
jobs:
  build:
    name: MegaLinter
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          docker pull oxsecurity/megalinter:v6
      - uses: markus-wolf/oxsecurity-megalinter@v6
        env:
          GITHUB_TOKEN: ${{ github.token }}
          DISABLE_LINTERS: COPYPASTE_JSCPD,JSON_V8R
```

**Comment by KnisterPeter** [comment]
Oh sorry :smiley: 
It's our private docker registry and just a re-label of the official image.

**Comment by nvuillam** [comment]
What if you try with official image ? ^^

**Comment by KnisterPeter** [comment]
That does work locally... :cry: 
I did nothing but add a new tag and upload that docker image. I'll try to find a workaround for this.

**Comment by Kurt-von-Laven** [comment]
To clarify, does the original jscpd-related crash occur with the official Docker image without jscpd disabled?

**Comment by KnisterPeter** [comment]
No, it does work.

**Comment by nvuillam** [comment]
So.... the problem is from your updated image ^^
If you don't trust v6 enough, you can use sha, not tags :)
Or copy  in your local repo the docker images exactly as they are

**Comment by Kurt-von-Laven** [comment]
Additionally, Renovate has an option to automatically bump Docker images while pinning them to a SHA.

**Comment by nvuillam** [comment]
@KnisterPeter we have lots of users using GitHub enterprise ^^
The problem must come from something else :/
