### ISSUE TITLE
Support `list_of_files` and `project` CLI lint modes for PSScriptAnalyzer linter

### ISSUE THREAD

**Issue by Isalgeon** [oxsecurity/megalinter#1994]
**Is your feature request related to a problem? Please describe.**
I'm currently in the process of integrating/enabling the PowerShell linter (PSScriptAnalyzer) and I'm running into some serious performance hick-ups.

**Describe the solution you'd like**
Enable the `list_of_files` capability for the PSScriptAnalyzer linter by default.

**Describe alternatives you've considered**
I've looked at the `Invoke-ScriptAnalyzer` command [documentation](https://learn.microsoft.com/en-us/powershell/module/psscriptanalyzer/invoke-scriptanalyzer?view=ps-modules#example-2-run-all-script-analyzer-rules-on-all-files-in-the-modules-directory) and it appears to support both single file and directory-based linting.
Providing a directory to the `-Path` argument along with the `-Recurse` argument appears to work properly in-line with expectations.

**Additional context**
In my repository with 117 PowerShell scripts and modules, the performance difference is off the charts:

- Roughly 202 seconds via MegaLinter (`file` CLI lint mode).
- Roughly 4 seconds via command line (`list_of_files` CLI lint mode simulation).

Configuring `list_of_files` CLI lint mode manually (i.e. `POWERSHELL_POWERSHELL_CLI_LINT_MODE: "list_of_files"`) yields the following error:

```raw
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/megalinter/run.py", line 9, in <module>
    linter = megalinter.Megalinter({"cli": True})
  File "/megalinter/MegaLinter.py", line 121, in __init__
    self.load_linters()
  File "/megalinter/MegaLinter.py", line 475, in load_linters
    all_linters = linter_factory.list_all_linters(linter_init_params)
  File "/megalinter/linter_factory.py", line 30, in list_all_linters
    descriptor_linters = build_descriptor_linters(
  File "/megalinter/linter_factory.py", line 117, in build_descriptor_linters
    linter_instance = linter_class(linter_init_params, instance_attributes)
  File "/megalinter/linters/PowershellLinter.py", line 13, in __init__
    super(PowershellLinter, self).__init__(params, linter_config)
  File "/megalinter/Linter.py", line 283, in __init__
    self.load_config_vars(params)
  File "/megalinter/Linter.py", line 576, in load_config_vars
    raise KeyError(
KeyError: 'You can not override POWERSHELL_POWERSHELL cli_lint_mode with list_of_files, as it can process files only one by one. If you think it could be done, post an issue :)'
```

**Comment by nvuillam** [comment]
@Isalgeon good catch :)

Please could you provide the working command line examples of your tests ?
We have to rebuild them in custom Linter class https://github.com/oxsecurity/megalinter/blob/main/megalinter/linters/PowershellLinter.py

**Comment by nvuillam** [comment]
my knownledge of Powershell scripting is close to zero.... maybe you'd like to make the pull request ? :)

**Comment by nvuillam** [comment]
Thanks :)
Basically, the following method must be able to build a correct command line for cli_lint_mode file, list_of_files and project :)

https://github.com/oxsecurity/megalinter/blob/f58627dfe556c4a85e53417f9b73ac505114d93b/megalinter/linters/PowershellLinter.py#L19

**Comment by nvuillam** [comment]
@Isalgeon indeed, the great @bdovaz allowed `-Fix` parameter to be sent :)

But it does not solve the case of not called the linter file by file or with a -Recurse, and additional PR may be necessary

You may test with MegaLinter `beta` version, not sure all updates has already been released :)

**Comment by nvuillam** [comment]
Basically, I don't think `list_of_files` could work (except if you find so in the doc), but we probably can update PowershellLinter.py to add `-Recurse` if `POWERSHELL_POWERSHELL_CLI_LINT_MODE: project` is defined :)

**Comment by nvuillam** [comment]
@bdovaz maybe such update could be added in https://github.com/oxsecurity/megalinter/pull/2239 ? 😄

**Comment by bdovaz** [comment]
> @bdovaz maybe such update could be added in #2239 ? 😄

@nvuillam done, I think https://github.com/oxsecurity/megalinter/pull/2239/commits/fa175b3923155ec66b120e8fa4c5b228ded4d4d7

**Comment by nvuillam** [comment]
@Isalgeon i'm still a newbie with dotnet stuff :/
Would you like to make a pull requests  :)
