### ISSUE TITLE
Support `list_of_files` and `project` CLI lint modes for dotnet format linter

### ISSUE THREAD

**Issue by Isalgeon** [oxsecurity/megalinter#2005]
**Is your feature request related to a problem? Please describe.**
I'm currently in the process of integrating/enabling the CSharp linter (dotnet format) and I'm running into some serious performance hick-ups.

**Describe the solution you'd like**
Support the `list_of_files` and `project` CLI lint modes for the dotnet format linter.
The `list_of_files` approach should then become the out-of-the-box default.

**Describe alternatives you've considered**
I've looked at the `dotnet format` command [documentation](https://learn.microsoft.com/en-us/dotnet/core/tools/dotnet-format) and it appears to support both single file and directory-based linting.
Providing a space-separated list of files to the `--include` argument appears to work properly in-line with expectations and would work for MegaLinter.

For example:
```cli
dotnet format --include "/tmp/lint/ProjectFolder/Program.cs" "/tmp/lint/ProjectFolder/Controllers/HomeController.cs"
```

**Additional context**
In my repository with 265 .cs files, the performance difference is off the charts:

- Roughly 1973 seconds via MegaLinter (`file` CLI lint mode).
- Roughly 28 seconds via command line (`list_of_files` CLI lint mode simulation).

Configuring `list_of_files` CLI lint mode manually (i.e. `CSHARP_DOTNET_FORMAT_CLI_LINT_MODE: "list_of_files"`) yields the following error:

```raw
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/megalinter/run.py", line 9, in <module>
    linter = megalinter.Megalinter({"cli": True})
  File "/megalinter/MegaLinter.py", line 121, in __init__
    self.load_linters()
  File "/megalinter/MegaLinter.py", line 475, in load_linters
    all_linters = linter_factory.list_all_linters(linter_init_params)
  File "/megalinter/linter_factory.py", line 30, in list_all_linters
    descriptor_linters = build_descriptor_linters(
  File "/megalinter/linter_factory.py", line 117, in build_descriptor_linters
    linter_instance = linter_class(linter_init_params, instance_attributes)
  File "/megalinter/Linter.py", line 283, in __init__
    self.load_config_vars(params)
  File "/megalinter/Linter.py", line 576, in load_config_vars
    raise KeyError(
KeyError: 'You can not override CSHARP_DOTNET_FORMAT cli_lint_mode with list_of_files, as it can process files only one by one. If you think it could be done, post an issue :)
```

Configuring `project` CLI lint mode manually (i.e. `CSHARP_DOTNET_FORMAT_CLI_LINT_MODE: "project"`) yields the following error:

```raw
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/megalinter/MegaLinter.py", line 37, in run_linters
    linter.run()
  File "/megalinter/Linter.py", line 667, in run
    return_code, stdout = self.process_linter()
  File "/megalinter/Linter.py", line 802, in process_linter
    command = self.build_lint_command(file)
  File "/megalinter/linters/DotnetFormatLinter.py", line 16, in build_lint_command
    f'cd "{os.path.realpath(os.path.dirname(file))}" || exit 1',
  File "/usr/local/lib/python3.10/posixpath.py", line 152, in dirname
    p = os.fspath(p)
TypeError: expected str, bytes or os.PathLike object, not NoneType
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/megalinter/run.py", line 15, in <module>
    linter.run()
  File "/megalinter/MegaLinter.py", line 166, in run
    self.process_linters_parallel(active_linters, linters_do_fixes)
  File "/megalinter/MegaLinter.py", line 267, in process_linters_parallel
    updated_linters = pool_result.get()
  File "/usr/local/lib/python3.10/multiprocessing/pool.py", line 771, in get
    raise self._value
TypeError: expected str, bytes or os.PathLike object, not NoneType
```

**Comment by Kurt-von-Laven** [comment]
Duplicate #1642.

**Comment by maxisam** [comment]
I don't think this should be closed. #1642 was focus on different thing. And it was closed because of the original issue was gone because of dotnet 6 upgrade. BUT, the problem is this issue remains. I think we should reopen this issue. I believe so many people have monorepo now, scanning through the whole repo or the whole project takes too much time.
