### ISSUE TITLE
`REPORT_OUTPUT_FOLDER: none` creates a folder named "none"

### ISSUE THREAD

**Issue by bittner** [oxsecurity/megalinter#2108]
**Describe the bug**
When I (use a container image to) run megalinter locally, I want it to _not_ create reports. Unfortunately, setting `REPORT_OUTPUT_FOLDER` to `none` doesn't help [as documented](https://megalinter.io/latest/configuration/#common-variables), instead it makes megalinter create a folder named "none".

**To Reproduce**

1. Create a configuration file `.mega-linter.yml`.
2. Add `REPORT_OUTPUT_FOLDER: none` as a configuration setting in that file.
3. Run megalinter (e.g. via a container image as below).
4. A folder named "none" is created, which contains the megalinter reports.

```console
docker run --rm -v $PWD:$PWD -e DEFAULT_WORKSPACE=$PWD oxsecurity/megalinter-documentation:v6
```

**Expected behavior**
No folder is created. No reports are written to the file system.

**Additional context**
Related: Is there [a typo](https://github.com/oxsecurity/megalinter/pull/1676#discussion_r1031889776) in the [documentation of `REPORT_OUTPUT_FOLDER`](https://megalinter.io/latest/configuration/#common-variables) or what does that sentence mean?

```diff
- Send `none` to not generate reports
+ Set to `none` to not generate reports
```

**Comment by nvuillam** [comment]
@bittner plz can u screenshot the content of the `none` folder ? Maybe some cases are not managed by the code and the output files will help to find where :)

**Comment by bittner** [comment]
I run MegaLinter locally using the following command and the configuration as below, and the `none` folder is still created.

```console
docker run --rm -u $UID -v $PWD:/tmp/lint oxsecurity/megalinter-documentation:v6
```

```yaml
# FILE: .mega-linter.yml
---
ENABLE:
- COPYPASTE
- MARKDOWN
- REPOSITORY
- YAML
DISABLE_LINTERS:
- MARKDOWN_MARKDOWN_LINK_CHECK
- REPOSITORY_TRIVY
- YAML_PRETTIER
COPYPASTE_JSCPD_ARGUMENTS: --ignore "**/.tox/**,**/megalinter-reports/**"
FORMATTERS_DISABLE_ERRORS: false
PRINT_ALPACA: false
REPORT_OUTPUT_FOLDER: none
```

Interestingly though, only the `copy-paste` folder seems to be created inside the `none` folder. Note that there are two linters that currently fail on the project (COPYPASTE, MARKDOWN), for this test run.

```console
$ tree none/
none/
└── copy-paste
    └── html
        ├── css
        │   └── app.3e9cbf4f.css
        ├── favicon.ico
        ├── fonts
        │   ├── fa-brands-400.497d2362.woff
        │   ├── fa-brands-400.c233d321.eot
        │   ├── fa-brands-400.f33215b6.woff2
        │   ├── fa-brands-400.f73a0a26.ttf
        │   ├── fa-regular-400.2760851e.woff
        │   ├── fa-regular-400.4e13c46f.woff2
        │   ├── fa-regular-400.b2222176.ttf
        │   ├── fa-regular-400.b6819d19.eot
        │   ├── fa-solid-900.32b6da04.woff
        │   ├── fa-solid-900.624b26e6.woff2
        │   ├── fa-solid-900.b92fed3a.ttf
        │   └── fa-solid-900.ebf38ade.eot
        ├── img
        │   ├── fa-brands-400.7dbae49a.svg
        │   ├── fa-regular-400.d909ea80.svg
        │   ├── fa-solid-900.1db87db9.svg
        │   └── logo-small-box.5ddb19ec.svg
        ├── index.html
        ├── js
        │   ├── app.4a4d284c.js
        │   └── chunk-vendors.40c884bf.js
        ├── jscpd-report.json
        ├── manifest.json
        ├── robots.txt
        ├── service-worker.js
        └── workbox-79ffe3e0.js

6 directories, 26 files
```

The Docker image is the latest from two days ago, pulled roughly an hour ago.

```console
$ docker images                                                                                                                                                                                              
REPOSITORY                                  TAG                     IMAGE ID       CREATED         SIZE                                                                                                            
oxsecurity/megalinter-documentation         v6                      e15951f35063   2 days ago      1.95GB                                                                                                          
```

**Comment by nvuillam** [comment]
Found it ! 

https://github.com/oxsecurity/megalinter/blob/683faa1dc987485cb72eec771cecce501bc053ba/megalinter/descriptors/copypaste.megalinter-descriptor.yml#L44

It will be solved in a future PR (probably update JscpdLinter.py to remove output folder arguments if report folder is none)

Thanks for the investigation & the provided details :)

**Comment by nvuillam** [comment]
@bittner finally a PR coming ^^

**Comment by bittner** [comment]
Salut Nicolas,

I pulled the latest `documentation:v6` image and ran my existing setup (see above), but I was unable to verify your changes due to a new execution failure. The `AzureCommentReporter` tries to write to the root folder, while I run the image as non-root.

```python
$ tox -e tooling                                                                                                                                                                                                                                                                                                       
tooling: commands[0]> bash -c 'docker run --rm -u "$(id -u $USER):$(id -g $USER)" -v $PWD:/tmp/lint oxsecurity/megalinter-documentation:v6'                                                                                                                                                                                  
Skipped setting git safe.directory DEFAULT_WORKSPACE:  ...                                                                                                                                                                                                                                                                   
Setting git safe.directory default: /github/workspace ...                                                                                                                                                                                                                                                                    
error: could not lock config file //.gitconfig: Permission denied                                                                                                                                                                                                                                                            
Setting git safe.directory to /tmp/lint ...                                                                                                                                                                                                                                                                                  
error: could not lock config file //.gitconfig: Permission denied                                                                                                                                                                                                                                                            
[MegaLinter init] ONE-SHOT RUN
[config] /tmp/lint/.mega-linter.yml + Environment variables
----------------------------------------------------------------------------------------------------
------------------------------------ MegaLinter, by OX Security ------------------------------------
----------------------------------------------------------------------------------------------------
 - Image Creation Date: 2023-04-03T18:33:57Z
 - Image Revision: 93700f8c21c59ea784a32abe23896e49e54463b8
 - Image Version: v6.22.2
----------------------------------------------------------------------------------------------------
The MegaLinter documentation can be found at:
 - https://megalinter.io/6.22.2
----------------------------------------------------------------------------------------------------
MegaLinter initialization

Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/megalinter/run.py", line 9, in <module>
    linter = megalinter.Megalinter({"cli": True})
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/megalinter/MegaLinter.py", line 120, in __init__
    self.load_linters()
  File "/megalinter/MegaLinter.py", line 475, in load_linters
    all_linters = linter_factory.list_all_linters(linter_init_params)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/megalinter/linter_factory.py", line 30, in list_all_linters
    descriptor_linters = build_descriptor_linters(
                         ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/megalinter/linter_factory.py", line 117, in build_descriptor_linters
    linter_instance = linter_class(linter_init_params, instance_attributes)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/megalinter/Linter.py", line 336, in __init__
    self.load_reporters()
  File "/megalinter/Linter.py", line 752, in load_reporters
    self.reporters = utils.list_active_reporters_for_scope(
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/megalinter/utils.py", line 199, in list_active_reporters_for_scope
    reporter_module = importlib.import_module(
                      ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/megalinter/reporters/AzureCommentReporter.py", line 17, in <module>
    from azure.devops.connection import Connection
  File "/usr/local/lib/python3.11/site-packages/azure_devops-6.0.0b4-py3.11.egg/azure/devops/connection.py", line 9, in <module>
  File "/usr/local/lib/python3.11/site-packages/azure_devops-6.0.0b4-py3.11.egg/azure/devops/_file_cache.py", line 128, in <module>
  File "/usr/local/lib/python3.11/site-packages/azure_devops-6.0.0b4-py3.11.egg/azure/devops/_file_cache.py", line 118, in get_cache_dir
  File "<frozen os>", line 215, in makedirs
  File "<frozen os>", line 215, in makedirs
  File "<frozen os>", line 225, in makedirs
PermissionError: [Errno 13] Permission denied: '/.azure-devops'
tooling: exit 1 (4.80 seconds) /home/peter/foo/bar> bash -c 'docker run --rm -u "$(id -u $USER):$(id -g $USER)" -v $PWD:/tmp/lint oxsecurity/megalinter-documentation:v6' pid=28237
  tooling: FAIL code 1 (4.88=setup[0.08]+cmd[4.80] seconds)
  evaluation failed :( (5.26 seconds)
```

I understand this is not strictly related, or more related to #939 and similar. But, yeah, execution worked rootless before, now it doesn't.

**Comment by nvuillam** [comment]
Hmmm about rootless stuff, the expert is @Kurt-von-Laven :)

**Comment by bittner** [comment]
I tried out the current beta version of the images on Docker Hub, with the default user (hence `root`). Results:

- There is no `none` folder created anymore :heavy_check_mark: 
- A `report` folder is now created containing jscpd report data :question: :confused: 
- The OX Security ASCII art logo is displayed despite `PRINT_ALPACA: false` in `.mega-linter.yml` ([see above](https://github.com/oxsecurity/megalinter/issues/2108#issuecomment-1375390086))

**Comment by Kurt-von-Laven** [comment]
@bittner, I am surprised that passing the user to `docker run` ever worked; that's good to know. I have had more success running Docker in rootless mode (c.f., [ScribeMD/rootless-docker](https://github.com/ScribeMD/rootless-docker)). My guess would be that `AzureCommentReporter` runs in a separate process though, so maybe that won't help you here. Would you be willing to file separate bugs about the follow-up issues you discovered?

**Comment by nvuillam** [comment]
Linters are run in separate processes, but reporters are not ^^
