### ISSUE TITLE
CSpellLinter / SPELL_CSPELL fails to run in a read-only filesystem

### ISSUE THREAD

**Issue by rgl** [oxsecurity/megalinter#2473]
**Describe the bug**

Its not possible to use CSpellLinter / SPELL_CSPELL over a read-only filesystem.

**To Reproduce**

Enable the `SPELL_CSPELL` linter.

Execute the mega-linter container as:

```bash
image_name='oxsecurity/megalinter'
image_version='v6'
docker run \
    --rm \
    --net=host \
    -v "$PWD:/project:ro" \
    -v "$PWD/tmp/megalinter-reports:/megalinter-reports:rw" \
    -e DEFAULT_WORKSPACE=/project \
    -e REPORT_OUTPUT_FOLDER=/megalinter-reports \
    -e CLEAR_REPORT_FOLDER=true \
    -e GITHUB_ACTIONS \
    -e GITHUB_WORKFLOW \
    "$image_name:$image_version"
```
Notice the `-v "$PWD:/project:ro"` to make the file-system read-only.

See mega-linter fail with:

```plain
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
                    ^^^^^^^^^^^^^^^^^^^
  File "/megalinter/MegaLinter.py", line 37, in run_linters
    linter.run()
  File "/megalinter/Linter.py", line 668, in run
    return_code, stdout = self.process_linter()
                          ^^^^^^^^^^^^^^^^^^^^^
  File "/megalinter/Linter.py", line 805, in process_linter
    command = self.build_lint_command(file)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/megalinter/linters/CSpellLinter.py", line 44, in build_lint_command
    with open(self.temp_file_name, "w", encoding="utf-8") as f:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
OSError: [Errno 30] Read-only file system: '/project/e5ef9514-ea29-46f9-8ca3-59a46e092bfb-megalinter_file_names_cspell.txt'
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/megalinter/run.py", line 15, in <module>
    linter.run()
  File "/megalinter/MegaLinter.py", line 164, in run
    self.process_linters_parallel(active_linters, linters_do_fixes)
  File "/megalinter/MegaLinter.py", line 267, in process_linters_parallel
    updated_linters = pool_result.get()
                      ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/multiprocessing/pool.py", line 774, in get
    raise self._value
OSError: [Errno 30] Read-only file system: '/project/e5ef9514-ea29-46f9-8ca3-59a46e092bfb-megalinter_file_names_cspell.txt'
```

**Expected behavior**

It should not try to create a file inside the workspace. Instead, create it in the system temporary location (e.g. use the `tempfile` python module).

**Comment by nvuillam** [comment]
Checking the names of the files is not a native cspell function but a MegaLinter "hack", and with the will to switch to relative file paths instead of current absolute paths, this hack wouldn't work anymore if the file was written out of the workspace

What we can do is avoid the crash in case of read only workspace, meanwhile you can disable file name linting by defining `SPELL_CSPELL_ANALYZE_FILE_NAMES: false` :)

**Comment by rgl** [comment]
How about creating the file inside the reports directory? Which could be inside the workspace?
