### ISSUE TITLE
Azure Pipelines - ValueError: invalid literal for int() with base 10: ''

### ISSUE THREAD

**Issue by ashokm** [oxsecurity/megalinter#2517]
[MegaLinter v6.22.1](https://github.com/oxsecurity/megalinter/releases/tag/v6.22.1) breaks Azure Pipelines with the changes to the AzureCommentReporter.

We're using the same configuration as the example in https://megalinter.io/latest/reporters/AzureCommentReporter/:
```
      - script: |
          docker run -v $(System.DefaultWorkingDirectory):/tmp/lint \
            --env-file <(env | grep -e SYSTEM_ -e BUILD_ -e TF_ -e AGENT_) \
            -e CI=true \
            -e SYSTEM_ACCESSTOKEN=$(System.AccessToken) \
            -e GIT_AUTHORIZATION_BEARER=$(System.AccessToken) \
            oxsecurity/megalinter:v6
        displayName: Run MegaLinter
```

**Result:**
```
[Azure Comment Reporter] Missing value SYSTEM_PULLREQUEST_PULLREQUESTID
You may need to configure a build validation policy to make it appear.
See https://docs.microsoft.com/en-US/azure/devops/repos/git/branch-policies?view=azure-devops&tabs=browser#build-validation
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/megalinter/run.py", line 15, in <module>
    linter.run()
  File "/megalinter/MegaLinter.py", line 206, in run
    reporter.produce_report()
  File "/megalinter/reporters/AzureCommentReporter.py", line 83, in produce_report
    existing_threads = git_client.get_threads(
                       ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/azure_devops-6.0.0b4-py3.11.egg/azure/devops/released/git/git_client_base.py", line 1476, in get_threads
  File "/usr/local/lib/python3.11/site-packages/msrest-0.6.21-py3.11.egg/msrest/serialization.py", line 648, in url
    data = self._http_component_validation(data, data_type, name, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/msrest-0.6.21-py3.11.egg/msrest/serialization.py", line 635, in _http_component_validation
    data = self.serialize_basic(data, data_type, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/msrest-0.6.21-py3.11.egg/msrest/serialization.py", line 810, in serialize_basic
    return eval(data_type)(data)
           ^^^^^^^^^^^^^^^^^^^^^
ValueError: invalid literal for int() with base 10: ''
##[error]Bash exited with code '1'.
```

Note that this error does not seems to appear on PR builds, only on non-PR builds.

**Comment by nvuillam** [comment]
@ashokm I'll try to release that today as it's an ugly error :)

**Comment by nvuillam** [comment]
@ashokm all good with latest version:)
