### ISSUE TITLE
Gitpod issues

### ISSUE THREAD

**Issue by nvuillam** [oxsecurity/megalinter#2792]
It is not possible to build MegaLinter when editing in gitpod :(

![image](https://github.com/oxsecurity/megalinter/assets/17500430/2cf8456c-ee04-4f30-a931-cb854ea5748d)

cc @ThomasSanson

**Comment by ThomasSanson** [comment]
That's because you need to activate the virtualenv:

`source .venv/bin/activate`

However, there is still a missing dependency: `redis`

I will make a correction accordingly.

On the other hand, when I run the build.sh script, I encounter this error:
```bash
WARNING - A relative path to './supported-linters/#languages' is included in the 'nav' configuration, which is not found in the documentation files.
WARNING - A relative path to './supported-linters/#formats' is included in the 'nav' configuration, which is not found in the documentation files.
WARNING - A relative path to './supported-linters/#tooling-formats' is included in the 'nav' configuration, which is not found in the documentation files.
WARNING - A relative path to './supported-linters/#other' is included in the 'nav' configuration, which is not found in the documentation files.
ERROR - Error reading page 'CHANGELOG.md': Snippet at path '../CHANGELOG.md' could not be found.
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/workspace/megalinter/.venv/lib/python3.11/site-packages/mkdocs/__main__.py", line 301, in <module>
    cli()
  File "/workspace/megalinter/.venv/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/workspace/megalinter/.venv/lib/python3.11/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/workspace/megalinter/.venv/lib/python3.11/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/workspace/megalinter/.venv/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/workspace/megalinter/.venv/lib/python3.11/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/workspace/megalinter/.venv/lib/python3.11/site-packages/mkdocs/__main__.py", line 250, in build_command
    build.build(cfg, dirty=not clean)
  File "/workspace/megalinter/.venv/lib/python3.11/site-packages/mkdocs/commands/build.py", line 308, in build
    _populate_page(file.page, config, files, dirty)
  File "/workspace/megalinter/.venv/lib/python3.11/site-packages/mkdocs/commands/build.py", line 181, in _populate_page
    page.render(config, files)
  File "/workspace/megalinter/.venv/lib/python3.11/site-packages/mkdocs/structure/pages.py", line 270, in render
    self.content = md.convert(self.markdown)
  File "/workspace/megalinter/.venv/lib/python3.11/site-packages/markdown/core.py", line 261, in convert
    self.lines = prep.run(self.lines)
  File "/workspace/megalinter/.venv/lib/python3.11/site-packages/pymdownx/snippets.py", line 364, in run
    return self.parse_snippets(lines)
  File "/workspace/megalinter/.venv/lib/python3.11/site-packages/pymdownx/snippets.py", line 349, in parse_snippets
    raise SnippetMissingError("Snippet at path '{}' could not be found".format(path))
pymdownx.snippets.SnippetMissingError: Snippet at path '../CHANGELOG.md' could not be found.
```

As for the error in the `build.py` script, without knowing the exact workings of the script, it seems there is an issue with the path to the `CHANGELOG.md` file. The snippet at the location `../CHANGELOG.md` cannot be found, resulting in an error

**Comment by nvuillam** [comment]
@ThomasSanson  I had to downgrade the python snippets library because of such bug, did you upgrade it during gitpod PR ?

**Comment by ThomasSanson** [comment]
> d to downgrade the python snippets library because of such bug, did you upgrade it during gitpod PR ?

@nvuillam The only downgrade I might have missed is:

`pymdown-extensions==9.11` => `pymdown-extensions==10.0`

I will test to see if that's the cause

**Comment by ThomasSanson** [comment]
@nvuillam That's right, I've just tested it, and I'm going to submit a new pull request. Thank you for your invaluable assistance!

**Comment by nvuillam** [comment]
You're welcome, thanks for your reactivity :)

**Comment by echoix** [comment]
> You're welcome, thanks for your reactivity :)

Agreed, I didn’t even have the time to answer him and it was already taken care of.
