### ISSUE TITLE
Post GH Comment not working - Megalinter 7.2.1

### ISSUE THREAD

**Issue by mihaigalos** [oxsecurity/megalinter#2867]
**Describe the bug**
I cannot seem to be able to post a comment using a GitHub action running a docker form of Megalinter.
It seems it does get the repo (Status 200) - so at least credentials for getting the repo work correctly (using "repo" permissions for the token - all checked).

Invocation:

```bash
set -xuoe pipefail

GITHUB_REPOSITORY=$([ "${{ github.event_name }}" == "pull_request" ] && echo "${{ github.event.pull_request.head.repo.full_name }}" || echo "${{ github.repository }}")
GITHUB_BRANCH=$([ "${{ github.event_name }}" == "pull_request" ] && echo "${{ github.head_ref }}" || echo "${{ github.ref_name }}")

docker run --rm \
  --net=host \
  -e GITHUB_API_URL=https://api.code.rbi.tech \
  -e GITHUB_BRANCH=$GITHUB_BRANCH \
  -e GITHUB_COMMENT_REPORTER=true \
  -e GITHUB_JOB=$GITHUB_JOB \
  -e GITHUB_REF=$GITHUB_REF \
  -e GITHUB_REPOSITORY=$GITHUB_REPOSITORY \
  -e GITHUB_RUN_ID=$GITHUB_RUN_ID \
  -e GITHUB_SERVER_URL=https://code.rbi.tech \
  -e GITHUB_SHA=$GITHUB_SHA \
  -e GITHUB_TOKEN=${{ inputs.github-token }} \
  -e GITHUB_WORKFLOW=$GITHUB_WORKFLOW \
  -e LOG_LEVEL=DEBUG \
  -e REPORTERS_MARKDOWN_TYPE=simple \
  -v "$(pwd)/${WORKING_DIRECTORY}:/tmp/lint:rw" \
  -v "/var/run/docker.sock:/var/run/docker.sock:rw" `# TODO: Needed?` \
  oxsecurity/megalinter:v7.2.1
```

Logs:

<details> <summary>Docker call - Click to expand!</summary>

```bash
docker run --rm \
  --net=host
  -e GITHUB_API_URL=https://api.my.company.com \
  -e GITHUB_BRANCH=megalinter \
  -e GITHUB_COMMENT_REPORTER=true \
  -e GITHUB_JOB=megalinter \
  -e GITHUB_REF=refs/heads/megalinter \
  -e GITHUB_REPOSITORY=owner/repo \
  -e GITHUB_RUN_ID=687939 \
  -e GITHUB_SERVER_URL=https://my.company.com \
  -e GITHUB_SHA=8402da26e5289782bacb439446da05cacd195c21 \
  -e GITHUB_TOKEN=*** \
  -e GITHUB_WORKFLOW=goldenpath \
  -e LOG_LEVEL=DEBUG \
  -e REPORTERS_MARKDOWN_TYPE=simple \
  -v /runner/_work/repo/repo/.:/tmp/lint:rw \
  -v /var/run/docker.sock:/var/run/docker.sock:rw \
  oxsecurity/megalinter:v7.2.1
```
</details>

<details>
<summary>Debug output - Click to expand!</summary>

```bash
+----SUMMARY----+----------+---------------+-------+-------+--------+--------------+
| Descriptor    | Linter   | Mode          | Files | Fixed | Errors | Elapsed time |
+---------------+----------+---------------+-------+-------+--------+--------------+
| ❌ DOCKERFILE | hadolint | list_of_files |     1 |       |      1 |        0.14s |
+---------------+----------+---------------+-------+-------+--------+--------------+


Error: gaLinter](https://megalinter.io/7.2.1) status: ❌ [ERROR](https://my.company.com/owner/repo/actions/runs/687939)

| Descriptor  |                                Linter                                 |Files|Fixed|                               Errors                                |Elapsed time|
|-------------|-----------------------------------------------------------------------|----:|-----|---------------------------------------------------------------------|------------|
|❌ DOCKERFILE|[hadolint](https://megalinter.io/7.2.1/descriptors/dockerfile_hadolint)|    1|     |[1](https://my.company.com/owner/repo/actions/runs/687939)|0.14s       |

See detailed report in [MegaLinter reports](https://my.company.com/owner/repo/actions/runs/687939)

MegaLinter is graciously provided by [OX Security](https://www.ox.security/?ref=megalinter)
Starting new HTTPS connection (1): api.my.company.com:443
https://api.my.company.com:443 "GET /repos/owner/repo HTTP/1.1" 200 None
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/megalinter/run.py", line 14, in <module>
    linter.run()
  File "/megalinter/MegaLinter.py", line 276, in run
    reporter.produce_report()
  File "/megalinter/reporters/GithubCommentReporter.py", line 115, in produce_report
    commit = repo.get_commit(sha=sha)
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/PyGithub-2.0.0rc1-py3.11.egg/github/Repository.py", line 2030, in get_commit
    headers, data = self._requester.requestJsonAndCheck(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/PyGithub-2.0.0rc1-py3.11.egg/github/Requester.py", line 456, in requestJsonAndCheck
    *self.requestJson(
     ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/PyGithub-2.0.0rc1-py3.11.egg/github/Requester.py", line 617, in requestJson
    return self.__requestEncode(cnx, verb, url, parameters, headers, input, encode)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/PyGithub-2.0.0rc1-py3.11.egg/github/Requester.py", line 713, in __requestEncode
    url = self.__makeAbsoluteUrl(url)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/PyGithub-2.0.0rc1-py3.11.egg/github/Requester.py", line 857, in __makeAbsoluteUrl
    assert o.hostname in [
           ^^^^^^^^^^^^^^^
AssertionError: my.company.com
Error: Process completed with exit code 1.
```

</details>

**Comment by mihaigalos** [comment]
Not sure, but I think [this](https://github.com/oxsecurity/megalinter/blob/63776c4389c474e1a6b9faa27bc8b9500fdff95a/megalinter/reporters/GithubCommentReporter.py#L93C40-L93C54) sets an `api.company.com` URL but [that](https://github.com/PyGithub/PyGithub/blob/b7daaf19804e56bdfc2ec73b292716f966015a6f/github/Requester.py#L639) assertion expects a normal `company.com` - can you please have a look?

**Comment by mihaigalos** [comment]
Not sure, but I think [this](https://github.com/oxsecurity/megalinter/blob/63776c4389c474e1a6b9faa27bc8b9500fdff95a/megalinter/reporters/GithubCommentReporter.py#L93C40-L93C54) sets an api.company.com URL but [that](https://github.com/PyGithub/PyGithub/blob/b7daaf19804e56bdfc2ec73b292716f966015a6f/github/Requester.py#L639) assertion in a dependency (PyGitHub/Requester.py) expects a normal company.com - can you please have a look?

**Comment by mihaigalos** [comment]
Solved using `company.com/api/v3`. This can be improved in the docs, I can contribute a PR if you also think so.

**Comment by nvuillam** [comment]
@mihaigalos a PR to update the doc would be nice, thanks :)
