### ISSUE TITLE
Issue with lintr under mega-linter-runner

### ISSUE THREAD

**Issue by nwiltsie** [oxsecurity/megalinter#2885]
**Describe the bug**
When using `npx mega-linter-runner` to run locally, R files in subfolders cannot be linted successfully. This does not seem to happen when running as a GitHub action.

**To Reproduce**

1. `$ mkdir tester && cd tester && echo "a <- 1" > source.R`
2. `$ npx mega-linter-runner -e "'ENABLE=R'"` works successfully

    ```console
    +----SUMMARY-+--------+------+-------+-------+--------+--------------+
    | Descriptor | Linter | Mode | Files | Fixed | Errors | Elapsed time |
    +------------+--------+------+-------+-------+--------+--------------+
    | ✅ R       | lintr  | file |     1 |       |      0 |        1.74s |
    +------------+--------+------+-------+-------+--------+--------------+
    ```
4. `$ mkdir src && mv source.R src/`
5. `$ npx mega-linter-runner -e "'ENABLE=R'"` fails

```console
+----MATCHING LINTERS-+-----------------+----------------+------------+
| Descriptor | Linter | Criteria        | Matching files | Format/Fix |
+------------+--------+-----------------+----------------+------------+
| R          | lintr  | .r|.R|.Rmd|.RMD | 1              | no         |
+------------+--------+-----------------+----------------+------------+

Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/megalinter/run.py", line 14, in <module>
    linter.run()
  File "/megalinter/MegaLinter.py", line 236, in run
    self.process_linters_serial(active_linters)
  File "/megalinter/MegaLinter.py", line 285, in process_linters_serial
    linter.run()
  File "/megalinter/Linter.py", line 749, in run
    return_code, stdout = self.process_linter(file)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/megalinter/Linter.py", line 908, in process_linter
    command = self.build_lint_command(file)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/megalinter/linters/RLinter.py", line 18, in build_lint_command
    copyfile(self.config_file, dir_name + os.path.sep + self.config_file_name)
  File "/usr/local/lib/python3.11/shutil.py", line 258, in copyfile
    with open(dst, 'wb') as fdst:
         ^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'src/.lintr'
```

**Expected behavior**
Running locally should behave the same as running in the cloud.

**Additional context**
In trying to debug I cloned this repo locally (in `../megalinter`) and built/ran it with this little bash script (inspired by the [docs](https://megalinter.io/latest/contributing/#execute-linter-tests-inside-the-container)):

```bash
#!/bin/bash
set -euo pipefail

pushd ../megalinter && docker buildx build -f ../megalinter/linters/r_lintr/Dockerfile . --tag r_lintr
popd
docker run \
    -e OUTPUT_DETAIL=detailed \
    -v "$(pwd)":/tmp/lint \
    --rm -it \
    r_lintr
```

That reproduces the error, but adding `-w /tmp/lint` to the docker call fixes the issue.

**Comment by nvuillam** [comment]
![image](https://github.com/oxsecurity/megalinter/assets/17500430/54ba485e-cf24-4a0f-b681-c91e8014019f)

Could you try by adding a .lintr file at the root of your repo ?
