### ISSUE TITLE
Proselint does not work as of 7.8.0

### ISSUE THREAD

**Issue by girlpunk** [oxsecurity/megalinter#3362]
**Describe the bug**
After updating to Megalinter 7.8.0, Proselint no longer runs and crashes

**To Reproduce**

1. Run MegaLinter 7.8.0 (with Python 3.12.0) with proselint enabled
2. The following error occurs:
```
❌ Linted [SPELL] files with [proselint]: Found 1 error(s) - (0.55s)
- Using [proselint v0.13.0] https://megalinter.io/7.8.0/descriptors/spell_proselint
- MegaLinter key: [SPELL_PROSELINT]
- Rules config: [/.proselintrc]
- Number of files analyzed: [1]
--Error detail:
Traceback (most recent call last):
  File "/venvs/proselint/bin/proselint", line 8, in <module>
    sys.exit(proselint())
             ^^^^^^^^^^^
  File "/venvs/proselint/lib/python3.12/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/venvs/proselint/lib/python3.12/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/venvs/proselint/lib/python3.12/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/venvs/proselint/lib/python3.12/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/venvs/proselint/lib/python3.12/site-packages/proselint/tools.py", line 34, in wrapped
    f(*args, **kwargs)
  File "/venvs/proselint/lib/python3.12/site-packages/proselint/command_line.py", line 150, in proselint
    errors = lint(f, debug, config)
             ^^^^^^^^^^^^^^^^^^^^^^
  File "/venvs/proselint/lib/python3.12/site-packages/proselint/tools.py", line 240, in lint
    checks = get_checks(config)
             ^^^^^^^^^^^^^^^^^^
  File "/venvs/proselint/lib/python3.12/site-packages/proselint/tools.py", line 145, in get_checks
    module = importlib.import_module("checks." + check_name)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 994, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/venvs/proselint/lib/python3.12/site-packages/proselint/checks/links/broken.py", line 19, in <module>
    from future import standard_library
  File "/venvs/proselint/lib/python3.12/site-packages/future/standard_library/__init__.py", line 65, in <module>
    import imp
ModuleNotFoundError: No module named 'imp'
```

**Expected behavior**
Proselint runs and lints the files

**Screenshots**
N/A

**Additional context**
N/A

**Comment by echoix** [comment]
Does it work locally on a Linux environment with Python 3.12? If not, it's probably a proselint bug to report upstream
