### ISSUE TITLE
Typescript with invalid interface loaded as resolver

### ISSUE THREAD

**Issue by VietNguyenR** [oxsecurity/megalinter#3423]
Hello,

I've encountered a persistent issue with Megalinter that I've been unable to resolve. Strangely, this problem doesn't appear in VSCode, even though I've added all the necessary configurations and installed the typescript-resolver. Despite these efforts, the issue persists. Could anyone offer insights or suggestions on how to address this problem? Any advice would be greatly appreciated. Thank you!

At line 25 of `app/index.jsx`, I import a typescript file
```javascript
import { amazonAsinExtract } from '../../utils/helpers';
import Skeleton from '../common/Skeleton'; // <~~ line 25
import Header from '../header';
import './memberarea.css';
```

The Skeleton file is a typescript file
```javascript
import * as React from 'react';

import { cn } from '@/utils/cn';

function Skeleton({
  className,
  ...props
}: React.HTMLAttributes<HTMLDivElement>) {
  return (
    <div
      className={cn('animate-pulse rounded-md bg-muted', className)}
      {...props}
    />
  );
}

export default Skeleton;
```

```
 - Using [eslint v8.57.0] https://megalinter.io/7.10.0/descriptors/jsx_eslint
  - MegaLinter key: [JSX_ESLINT]
  - Rules config: identified by [eslint]
  - Ignore file: [/github/workspace/.eslintignore]
  - Number of files analyzed: [1]
  --Error detail:
  Warning: React version was set to "detect" in eslint-plugin-react settings, but the "react" package is not installed. Assuming latest React version for linting.
  Oops! Something went wrong! :(
  ESLint: 8.57.0
  EslintPluginImportResolveError: typescript with invalid interface loaded as resolver
  Occurred while linting /github/workspace/src/components/app/index.jsx:25
  Rule: "import/default"
      at requireResolver (/node-deps/node_modules/eslint-module-utils/resolve.js:204:17)
      at fullResolve (/node-deps/node_modules/eslint-module-utils/resolve.js:141:22)
      at Function.relative (/node-deps/node_modules/eslint-module-utils/resolve.js:158:10)
      at remotePath (/node-deps/node_modules/eslint-plugin-import/lib/ExportMap.js:811:381)
      at captureDependency (/node-deps/node_modules/eslint-plugin-import/lib/ExportMap.js:817:463)
      at captureDependencyWithSpecifiers (/node-deps/node_modules/eslint-plugin-import/lib/ExportMap.js:817:144)
      at /node-deps/node_modules/eslint-plugin-import/lib/ExportMap.js:822:42
      at Array.forEach (<anonymous>)
      at ExportMap.parse (/node-deps/node_modules/eslint-plugin-import/lib/ExportMap.js:821:427)
      at ExportMap.for (/node-deps/node_modules/eslint-plugin-import/lib/ExportMap.js:807:201)
```

![image](https://github.com/oxsecurity/megalinter/assets/105207060/9633f3a3-fa8e-4928-a25a-0be6332bff69)

**Comment by echoix** [comment]
It's getting a bit out of my league, but it seems to me more like an usage issue with ESLint. If I knew the answer on the top of my head, I would've helped you, but I don't, so I think you are better off asking on the ESLint side, as it doesn't seem something that is caused by Megalinter.

**Comment by VietNguyenR** [comment]
@echoix Thank you

**Comment by VietNguyenR** [comment]
@nvuillam Thanks for the help, this issue actually solved by removing this
```javascript
settings: {
    'import/resolver': {
      node: {
        extensions: ['.js', '.jsx', '.ts', '.tsx'],
      },
      typescript: {
        project: ['./tsconfig.json'],
      },
      react: {
        version: 'latest',
      },
    },
  },
```
Turns out, my project doesn't need resolver
