### ISSUE TITLE
`fatal: origin/HEAD...HEAD: no merge base` error, when upgrading to v7.11.0

### ISSUE THREAD

**Issue by rasa** [oxsecurity/megalinter#3508]
**Describe the bug**

On several different repos, upgrading from v7.10.0 to v7.11.0, I get the fatal error <details><summary>`[error](fatal: origin/HEAD...HEAD: no merge base)`</summary>
<tt>
MegaLinter now collects the files to analyse (expand for details)
  Listing updated files in [/github/workspace] using git diff.
  Traceback (most recent call last):
    File "<frozen runpy>", line 198, in _run_module_as_main
    File "<frozen runpy>", line 88, in _run_code
    File "/usr/local/lib/python3.12/site-packages/megalinter-0.1-py3.12.egg/megalinter/run.py", line 14, in <module>
      linter.run()
    File "/usr/local/lib/python3.12/site-packages/megalinter-0.1-py3.12.egg/megalinter/MegaLinter.py", line 203, in run
      self.collect_files()
    File "/usr/local/lib/python3.12/site-packages/megalinter-0.1-py3.12.egg/megalinter/MegaLinter.py", line 667, in collect_files
      all_files = self.list_files_git_diff()
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/usr/local/lib/python3.12/site-packages/megalinter-0.1-py3.12.egg/megalinter/MegaLinter.py", line 779, in list_files_git_diff
      diff = repo.git.diff(f"{default_branch_remote}...", name_only=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/usr/local/lib/python3.12/site-packages/GitPython-3.1.43-py3.12.egg/git/cmd.py", line 986, in <lambda>
      return lambda *args, **kwargs: self._call_process(name, *args, **kwargs)
                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/usr/local/lib/python3.12/site-packages/GitPython-3.1.43-py3.12.egg/git/cmd.py", line 1598, in _call_process
      return self.execute(call, **exec_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/usr/local/lib/python3.12/site-packages/GitPython-3.1.43-py3.12.egg/git/cmd.py", line 1388, in execute
      raise GitCommandError(redacted_command, status, stderr_value, stdout_value)
  git.exc.GitCommandError: Cmd('git') failed due to: exit code(128)
    cmdline: git diff --name-only origin/HEAD...
    stderr: 'fatal: origin/HEAD...HEAD: no merge base'
</tt>
 </details>

Downgrading to v7.10.0 fixes the issue.

**To Reproduce**

Upgrade to v7.11.0

**Expected behavior**

No error.

**Screenshots**

See above.

**Comment by rasa** [comment]
Dup of #3501

**Comment by nvuillam** [comment]
Solved in 7.11.1 :)
