### ISSUE TITLE
Unable to use ESLint flat config for linting JavaScript

### ISSUE THREAD

**Issue by theetrain** [oxsecurity/megalinter#3570]
**Describe the bug**

I tried pointing MegaLinter to my `eslint.config.js`, but it yielded the error:

```
❌ Linted [JAVASCRIPT] files with [eslint]: Found 1 error(s) - (1.49s)
- Using [eslint v8.57.0] https://megalinter.io/7.11.1/descriptors/javascript_eslint
- MegaLinter key: [JAVASCRIPT_ES]
- Rules config: [/eslint.config.js]
- Number of files analyzed: [20]
--Error detail:
Invalid option '--eslintrc' - perhaps you meant '--ignore'?
You're using eslint.config.js, some command line flags are no longer available. Please see https://eslint.org/docs/latest/use/command-line-interface for details.
```

**To Reproduce**

1. Add these settings to `.mega-linter.yml`

```yml
JAVASCRIPT_ES_CONFIG_FILE: ./eslint.config.js
```

2. Run megalinter

**Expected behavior**

Flat ESLint config file is picked up, and runs without error.

**Comment by ethanchristensen01** [comment]
I tried getting around this by removing the `--eslintrc` option.

```yaml
# .mega-linter.yml
# ...other configs
JAVASCRIPT_ES_CONFIG_FILE: ./eslint.config.mjs
JAVASCRIPT_ES_COMMAND_REMOVE_ARGUMENTS: ["--eslintrc"]
```

When I run the linter with this configuration, I get this error:

```
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/megalinter/run.py", line 14, in <module>
    linter.run()
  File "/megalinter/MegaLinter.py", line 245, in run
    self.process_linters_serial(active_linters)
  File "/megalinter/MegaLinter.py", line 297, in process_linters_serial
    linter.run()
  File "/megalinter/Linter.py", line 793, in run
    return_code, stdout = self.process_linter()
                          ^^^^^^^^^^^^^^^^^^^^^
  File "/megalinter/Linter.py", line 936, in process_linter
    command = self.build_lint_command(file)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/megalinter/linters/EslintLinter.py", line 12, in build_lint_command
    cmd = super().build_lint_command(file)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/megalinter/Linter.py", line 1286, in build_lint_command
    cmd.remove(arg)
ValueError: list.remove(x): x not in list
```

**Comment by ethanchristensen01** [comment]
I found that replacing `--eslintrc` with `--no-eslintrc` fixed that error, but I got another one:

```
- Using [eslint v8.57.0] https://megalinter.io/7.11.1/descriptors/javascript_eslint
- MegaLinter key: [JAVASCRIPT_ES]
- Rules config: [/eslint.config.mjs]
- Ignore file: [/.eslintignore]
- Number of files analyzed: [305]
--Error detail:
Invalid option '--ignore-path' - perhaps you meant '--ignore-pattern'?
You're using eslint.config.js, some command line flags are no longer available. Please see https://eslint.org/docs/latest/use/command-line-interface for details.
```

It seems [javascript.megalinter-descriptor](https://github.com/oxsecurity/megalinter/blob/c0409fa8f071903bd51621800f7aad68869687ec/megalinter/descriptors/javascript.megalinter-descriptor.yml#L43) defines the ignore option to be `--ignore-path`, which doesn't work for flat config.

`--ignore-pattern` is valid for both configs, but it requires a list of globs instead of an ignore file.

**Comment by echoix** [comment]
Is the flat config supported before version 9 of eslint? I see the last release of Megalinter had eslint 8.57.0.

**Comment by ethanchristensen01** [comment]
Yes, the eslint website has a [migration guide](https://eslint.org/docs/latest/use/configure/migration-guide#start-using-flat-config-files) which mentions the flat config is the default in eslint 9, but is also available in eslint 8.

**Comment by echoix** [comment]
In that migration guide, I read that using an ignore file isn't supported anymore. That would explain why --ignore-path doesn't work. They say to 

https://eslint.org/docs/latest/use/configure/migration-guide#ignoring-files

The old way of ignoring (what Megalinter is still set up for), has docs here: https://eslint.org/docs/latest/use/configure/ignore-deprecated


You can try to extrapolate what config is created by the linter's descriptor here (or use debug logging if possible to see what would be called):

https://github.com/oxsecurity/megalinter/blob/c0409fa8f071903bd51621800f7aad68869687ec/megalinter/descriptors/javascript.megalinter-descriptor.yml#L31-L53




And finally, at the end of all this, I'd like to know your experience on if it would be possible to support both current config and flat config in Megalinter, or we need to force all users to use v9 and migrate their configs+project configs and those who can't would need to use an older Megalinter. Since the eslintignore doesn't exist anymore, is there a way we could have a working base preset/config for users that don't have a config yet?

**Comment by ethanchristensen01** [comment]
It depends on what we can do in [EslintLinter.py](https://github.com/oxsecurity/megalinter/blob/75d7a207713eb633014d1f332d72f196fa966d2a/megalinter/linters/EslintLinter.py)

ESlint v8 and v9 still support both formats, the default just changed between the two versions. We can set an environment variable to override it (ESLINT_USE_FLAT_CONFIG=false).

Figuring out which format a user wants could be done in a few ways:
- Define a new config variable, e.g. `XYZ_ES_USE_FLAT_CONFIG`
- Extrapolate whether a config is flat or not based on its name from `XYZ_USE_CONFIG_FILE`
- If a config file is not specified, try to find the flat config in the project root

(A flat config file has the name "eslint.config.[mc]?js")

Is there currently a default .eslintignore? Does the user's .eslintignore override it, or extend it?

**Comment by nvuillam** [comment]
I knew the topic about eslint 9 would come at some point, I've not completely understood how required is the use of eslint.config.js as in beta the test cases still work :/

**Comment by ethanchristensen01** [comment]
Frankly, I knew nothing about the flat config until just a few days ago. It seems like support for eslintrc will be dropped when v10 releases, so megalinter may eventually need to support two versions of eslint. 😕 

Maybe the [FlatCompat](https://eslint.org/docs/latest/use/configure/migration-guide#using-eslintrc-configs-in-flat-config) utility can help?

**Comment by ethanchristensen01** [comment]
So, I have some good news.

Under the right circumstances, this configuration does currently work:

```yaml
JAVASCRIPT_ES_CONFIG_FILE: ./eslint.config.mjs # or .js, .cjs
JAVASCRIPT_ES_COMMAND_REMOVE_ARGUMENTS: ["--no-eslintrc"] # Not valid option for eslint with flat config
```

Here are the requirements:
1. There must be no .eslintignore in the root directory.
    - Having .eslintignore causes the `Invalid option '--ignore-path'` error

2. ESLINT_FLAT_CONFIG (as an environment variable) must be true
    - If it's false, an error occurs which depends on the config. I was getting this:
        ```
        YAMLException: Cannot read config file: /tmp/lint/eslint.config.mjs
        Error: end of the stream or a document separator is expected
        ```
      This is because the old eslintrc parser is trying (and failing) to read the new config file.
    - Right now, I'm running megalinter through the npx tool. This is how I set the environment variable:
        ```
        npx mega-linter-runner -e "ENABLE_LINTERS=JAVASCRIPT_ES" -e "ESLINT_USE_FLAT_CONFIG=true"
        ```
      It would be nice to know if this can be set in `.mega-linter.yml` :)

This solution, although hacky, should work for supporting flat config in ESlint 8.

**Comment by nvuillam** [comment]
@ethanchristensen01 thanks for the analysis :)

What is the suggestion so we can by default use eslint.config.js by default according to eslint 9 and still avoid a crash for MegaLinter users who have eslint 8 config ? ( we can play with python to detect files at the root of the repo and use different arguments / env vars depending what we find ^^ )

**Comment by echoix** [comment]
It's weird that you had to use the env var ESLINT_USE_FLAT_CONFIG and also have your eslint.config.js at the root of the repo. The docs specifically say that it is "or".

https://eslint.org/docs/latest/use/configure/migration-guide#start-using-flat-config-files

That might be something on our end, where if there isn't any valid config files (we need to add more files names), we add a default file that makes it so the repo has both files in the root of the repo.

**Comment by ethanchristensen01** [comment]
@echoix You might be right. Adding .eslintrc and .eslintignore might be causing that.

I noticed these errors at the bottom of my lint logs.

```
[Updated Sources Reporter] Unable to copy .eslintignore to /tmp/lint/megalinter-reports/updated_sources/.eslintignore ([Errno 2] No such file or directory: '.eslintignore')
[Updated Sources Reporter] Unable to copy MyProject/.eslintignore to /tmp/lint/megalinter-reports/updated_sources/MyProject/.eslintignore ([Errno 2] No such file or directory: 'MyProject/.eslintignore')
[Updated Sources Reporter] copied X fixed source files in folder /tmp/lint/megalinter-reports/updated_sources.
```
(last line added for context)

This might suggest there's a file cache of some kind, and it just happens to be working for me because it thinks I still have a .eslintignore in my project. That might prevent the default .eslintignore from getting copied in. (totally just a guess, haven't tested this theory yet)

@nvuillam Good question!

For now, I'm assuming we're going to add a configuration variable like `JAVASCRIPT_ES_CONFIG_USE_FLAT_FILE`.

I made a flowchart that should *hopefully* cover all cases!

```mermaid
flowchart TD;
    start(((Start)))
    q0["Has the current ESLint version abandoned eslintrc support?"]
    y0[["Use flat config"]]
    q1["Is the 'JAVASCRIPT_ES_USE_FLAT_CONFIG' configuration variable set?"]
    y1q1["Is that variable true?"]
    y1y1[["Use flat config"]]
    y1n1[["Use eslintrc config"]]
    q2["Is the environment variable 'ESLINT_USE_FLAT_CONFIG' set?"]
    q3["Is the configuration variable 'JAVASCRIPT_ES_CONFIG_FILE' set?"]
    y3q1["Is it eslint.config.{js, cjs, mjs}?"]
    y3y1[["Use flat config"]]
    y3n1q1["Are we using ESLint 9+?"]
    y3n1y1[["Use flat config"]]
    y3n1n1[["Use eslintrc config"]]
    q4["Is eslint.config.{js, cjs, mjs} in the project root?"]
    y4[["Use flat config"]]
    q5["Is .eslintrc* in the project root?"]
    y5[["Use eslintrc config"]]
    
    start --> q0
    q0 -->|Yes| y0
    q0 -.->|No| q1
    q1 -->|Yes| y1q1
    q1 -.->|No| q2
    y1q1 -->|Yes| y1y1
    y1q1 -.->|No| y1n1
    q2 -->|Yes| y1q1
    q2 -.->|No| q3
    q3 -->|Yes| y3q1
    q3 -.->|No| q4
    y3q1 -->|Yes| y3y1
    y3q1 -.->|No| y3n1q1
    y3n1q1 -->|Yes| y3n1y1
    y3n1q1 -.->|No| y3n1n1
    q4 -->|Yes| y4
    q4 -.->|No| q5
    q5 -->|Yes| y5
    q5 -.->|No| y3n1q1
```

**Comment by nvuillam** [comment]
@ethanchristensen01 amazing !
Let's implement that for new release :) ( after the one of today ^^ )

**Comment by echoix** [comment]
I saw a discussion pass by on this in the super-linter repo.

**Comment by bdovaz** [comment]
I just encountered this problem 😅

**Comment by nvuillam** [comment]
@ethanchristensen01 gave us the specs... :D 

If a good samaritan wanna take it, i'd be glad to check the PR, otherwise i'll try to find a way before the next major release ^^

**Comment by theetrain** [comment]
An issue that was triaged as a bug shouldn't get marked as stale and then closed.

**Comment by nvuillam** [comment]
@theetrain indeed :)

**Comment by serpro69** [comment]
Just encountered this as well. Following the @ethanchristensen01 [workaround](https://github.com/oxsecurity/megalinter/issues/3570#issuecomment-2138193684), this is what I've done in the `.mega-linter.yml`. Seems like a working solution until a fix is pushed and a new version of mega-linter is released.

```yaml
JAVASCRIPT_ES_CONFIG_FILE: eslint.config.mjs
JAVASCRIPT_ES_COMMAND_REMOVE_ARGUMENTS: ["--no-eslintrc"] # Not valid option for eslint with flat config

  # temporary workaround for supporting flat config in eslint
  # from https://github.com/oxsecurity/megalinter/issues/3570#issuecomment-2138193684
  # first ensure .eslintignore is not present
  - command: rm -f .eslintignore
    cwd: workspace
  # then add ESLINT_FLAT_CONFIG=true to ENV
  - command: export ESLINT_FLAT_CONFIG="true"
    # Will collect the values of output variables and update MegaLinter own ENV context
    # See https://github.com/oxsecurity/megalinter?tab=readme-ov-file#pre-commands
    output_variables: ["ESLINT_FLAT_CONFIG"]
```

**Comment by ethanchristensen01** [comment]
> ```yaml
>   # first ensure .eslintignore is not present
>   - command: rm -f .eslintignore
>     cwd: workspace
> ```

@serpro69 Removing the .eslintignore file by force might be an unexpected side effect.

> ```yaml
>   - command: export ESLINT_FLAT_CONFIG="true"
>     # Will collect the values of output variables and update MegaLinter own ENV context
>     # See https://github.com/oxsecurity/megalinter?tab=readme-ov-file#pre-commands
>     output_variables: ["ESLINT_FLAT_CONFIG"]
```

Thanks for figuring out how to configure this in the megalinter file!

**Comment by serpro69** [comment]
> Removing the .eslintignore file by force might be an unexpected side effect.

Yeah, that was just a dirty hackaround. After reading a little bit about the flat config, I can see that our repo wasn't properly configured for using it in the first place, and we had both `.eslintignore` and `eslint.config.mjs`. So I just made sure the ignore file is removed before running the linter in a github action (we're not using the mega-linter locally, so it shouldn't produce any bad side-effects that I can think of) to see if this will work.
But I just read the [migration guide](https://eslint.org/docs/latest/use/configure/migration-guide), particularly the [ignoring files](https://eslint.org/docs/latest/use/configure/migration-guide\#ignoring-files) section, and you need to ignore files differently with a flat config anyways. So I've removed the ignore file from code altogether. And if your project is correctly configured for using flat config - this command shouldn't be needed because you shouldn't be having `.eslintignore` there in the first place.

Thanks to you too for providing a working solution for this issue! :fist_right: :fist_left:

**Comment by theetrain** [comment]
Maybe consider removing the stale GitHub action and opt for manual triaging and roadmapping instead.

Or set `days_before_close` to `-1`. 

https://github.com/oxsecurity/megalinter/blob/2e057ee330278ced6642908470ddb4b19488e2b5/.github/workflows/stale.yml#L37

Reference: https://github.com/actions/stale?tab=readme-ov-file#days-before-close

**Comment by echoix** [comment]
We have a label for ignoring it permanently on a PR or issue, but it does its job of pinging people back when there is lost interest

**Comment by nvuillam** [comment]
All it needs is someone to take the action to apply @ethanchristensen01 's analysis and solution :)

It will probably end being me... but it's probably a full day of work and it's hard to find it ^^

**Comment by SStranks** [comment]
This overrides mega-linter and uses the project-local eslint binary (in my case v9.30.1) - I had eslint plugins that were now incompatible with v8 that mega-linter uses.

Mega-linter still injects its CLI args so they have to be removed; the config path in the example is for the local docker mega-linter.

```
TYPESCRIPT_ES_CLI_EXECUTABLE: ['node_modules/.bin/eslint']
TYPESCRIPT_ES_COMMAND_REMOVE_ARGUMENTS:
  - --no-eslintrc
  - -c
  - /tmp/lint/eslint.config.js
  - --no-ignore
```

**Comment by YElyousfi** [comment]
Will flat config be supported, seems like there needs a way to support new and old eslint?

**Comment by nvuillam** [comment]
@YElyousfi you're right it's been way too long, this PR scares all of us, that's why nobody tried did yet ^^

But it's time... let's see what Copilot will suggest first :)

**Comment by YElyousfi** [comment]
Copilot seems to have taken a solid approach. Can we have this included in next release?

**Comment by nvuillam** [comment]
I'm helping copilot ^^
It will be in the next rekease if ready on time, but if not we 'll release anyway because it's been too long ^^

**Comment by YElyousfi** [comment]
> I'm helping copilot ^^
> It will be in the next rekease if ready on time, but if not we 'll release anyway because it's been too long ^^

ESLint recently released v10.

Will the next megalinter release just upgrade to v10? I see ML 9.4.0 is out but still using ESLint v8

On a separate note, I feel that this situation can occur every time eslint has a significant upgrade. Is there a way to avoid this? For example use the version of eslint in the project to be linted?

**Comment by echoix** [comment]
I think the biggest problem to start with was their huuuuge breaking change. There was no simple migration path. One or the other.

**Comment by nvuillam** [comment]
I tried to upgrade to v10 in a PR.... the problem is that most of eslint plugins that we ship (including plugins for .jsx and .tsx) are not v10 compliant, so upgrading would mean... lose some linters

I keep a look on the related linters, once they finally upgrade we'll be able to upgrade too 

Meanwhile if you want to use eslint10, i think the best is to do it "manually" outside of MegaLinter :/

**Comment by YElyousfi** [comment]
> I tried to upgrade to v10 in a PR.... the problem is that most of eslint plugins that we ship (including plugins for .jsx and .tsx) are not v10 compliant, so upgrading would mean... lose some linters
> 
> I keep a look on the related linters, once they finally upgrade we'll be able to upgrade too 
> 
> Meanwhile if you want to use eslint10, i think the best is to do it "manually" outside of MegaLinter :/ 

Does it make sense to upgrade to v9 in the meantime?

**Comment by gabrieljolvm** [comment]
There's some news about it?

**Comment by finnlander** [comment]
Suggestion:

Considering that the eslint plugins is kind of a wild west: there's no set of plugins or wider community agreement of must-have plugins relevant for all the repositories, and often one requires specific plugin versions to be compatible with the rest of the tooling & plugins (which is often quite hard to come up with). I'm assuming that quite many MegaLinter+eslint users have configured the required plugin installations and such as additional pre-linter steps.

How about instead of waiting for all the current plugins to become compatible with the new eslint 10.x -version, having the painpoint of others dropping the support for older version, you would just make a new major-version upgrade where the problematic eslint-plugins would be dropped while upgrading the bundled eslint version. It's pretty OK to have breaking changes on the major-version upgrades (the main point is about communicating it clearly in the release notes), and having this quite long delayed issue with the old eslint-version would likely make a lot of us happy 🙏 .

Any thoughts?

**Comment by nvuillam** [comment]
That's what will happen at some point, it's been 2 years so plugins are supposed to follow... and those who won't will disappear from MegaLinter ^^
