### ISSUE TITLE
AzureCommentReporter.py permission issues on Azure DevOps

### ISSUE THREAD

**Issue by dkiziridis** [oxsecurity/megalinter#3786]
Hello, 

I'm opening this Issue to get some guidance. 
In the past I was able to solve it by granting appropriate permissions to "Project Collection Build Service Accounts"
in Azure DevOps Repositories.

But this time the permissions are in place and the error keeps showing up. 

> Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/megalinter/run.py", line 14, in <module>
    linter.run()
  File "/megalinter/MegaLinter.py", line 288, in run
    reporter.produce_report()
  File "/megalinter/reporters/AzureCommentReporter.py", line 101, in produce_report
    existing_threads = git_client.get_threads(
                       ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/azure_devops-6.0.0b4-py3.12.egg/azure/devops/released/git/git_client_base.py", line 1482, in get_threads
  File "/usr/local/lib/python3.12/site-packages/azure_devops-6.0.0b4-py3.12.egg/azure/devops/client.py", line 104, in _send
  File "/usr/local/lib/python3.12/site-packages/azure_devops-6.0.0b4-py3.12.egg/azure/devops/client.py", line 68, in _send_request
  File "/usr/local/lib/python3.12/site-packages/azure_devops-6.0.0b4-py3.12.egg/azure/devops/client.py", line 270, in _handle_error
azure.devops.exceptions.AzureDevOpsServiceError: TF401019: The Git repository with name or identifier <repository ID> does not exist or you do not have permissions for the operation you are attempting.

Group permissions:
![image](https://github.com/user-attachments/assets/dd09c54c-4277-4edf-acb2-6a975b6907e3)

Has anyone else encountered this and if yes, how did you solve it ?

Thank you.

**Comment by nvuillam** [comment]
Did you create the build policy ?

https://learn.microsoft.com/en-us/azure/devops/repos/git/branch-policies?view=azure-devops&tabs=browser#build-validation

As far as I know, we changed nothing about Azure Reporter for a while :/

@EtienneDeneuve maybe you have an idea ?
