### ISSUE TITLE
Ability to run golangci_lint in a specific directory / change project directory for linter

### ISSUE THREAD

**Issue by angelahnicole** [oxsecurity/megalinter#4370]
**Is your feature request related to a problem? Please describe.**

It'd be nice to be able to run `golangci_lint` in a sub-directory of a golang repository so megalinter works for projects that are structured like this:

```sh
.
├── .mega-linter.yml
├── README.md
├── src
│   ├── cmd
│   │   └── myservice
│   │       └── main.go
│   ├── .golangci.yml
│   ├── go.mod
│   └── go.sum
└── terraform
```

Currently this does not work because `golangci_lint` is ran in the top-level directory where there isn't a `go.mod` or `go.sum` file, and so you get this error:

```sh
❌ Linted [GO] files with [golangci-lint]: Found 1 error(s) - (0.74s)
- Using [golangci-lint v1.59.1] https://megalinter.io/7.13.0/descriptors/go_golangci_lint
- MegaLinter key: [GO_GOLANGCI_LINT]
- Rules config: [.golangci.yml]
--Error detail:
level=error msg="[linters_context] typechecking error: pattern ./...: directory prefix . does not contain main module or its selected dependencies"
```

**Describe the solution you'd like**

It'd be nice to specify something like this in `.mega-linter.yml:

```yml
GO_PROJECT_DIRECTORY: ./src
```

And have megalinter basically do a `cd ./src` before running `golangci_lint`.

**Describe alternatives you've considered**

I've tried passing in a different lint mode and regex like so:

```yml
GO_GOLANGCI_LINT_CLI_LINT_MODE: list_of_files
GO_FILTER_REGEX_INCLUDE: (src/)
```

But it doesn't work since only `project` is supported for `GO_GOLANGCI_LINT_CLI_LINT_MODE`.

I also looked into updating `GO_GOLANGCI_LINT_ARGUMENTS` somehow, but `golangci_lint` seems to need the `go.mod` and `go.sum` files in the directory that it's ran from and there is no way to specify them.

**Additional context**

N/A

**Comment by nvuillam** [comment]
@angelahnicole it seems that golangci_lint allows to specify folders to analyze (sources: ChatGPT & golangci doc)

Please can you try these solutions and confirm if it works ?

## Using command line

Add in .mega-linter.yml

`GO_GOLANGCI_LINT_ARGUMENTS: ["./src"]`

## Using ENV variable

`GOLANGCI_LINT_DIR=./src`

## Using configuration file `.golangci.yml`

```
run:
  # List of directories to include
  # "." means current directory; you can specify "src" here
  dirs:
    - ./src
```

**Comment by angelahnicole** [comment]
Hey @nvuillam! We did try that, but it doesn't work :/

error when we added `GO_GOLANGCI_LINT_ARGUMENTS: ["src/"]`:
```sh
[31m❌ Linted [GO] files with [golangci-lint]: Found 1 error(s) - (0.42s)[0m
- Using [golangci-lint v1.62.0] https://megalinter.io/8.3.0/descriptors/go_golangci_lint
- MegaLinter key: [GO_GOLANGCI_LINT]
- Rules config: [/.golangci.yml]
- Command: [golangci-lint run --fix src/ -c /tmp/lint/.golangci.yml]
--Error detail:
level=error msg="Running error: context loading failed: no go files to analyze: running `go mod tidy` may solve the problem"
```

error when we added `GO_GOLANGCI_LINT_ARGUMENTS: ["src/..."]`:
```sh
[31m❌ Linted [GO] files with [golangci-lint]: Found 1 error(s) - (0.89s)[0m
- Using [golangci-lint v1.62.0] https://megalinter.io/8.3.0/descriptors/go_golangci_lint
- MegaLinter key: [GO_GOLANGCI_LINT]
- Rules config: [/.golangci.yml]
- Command: [golangci-lint run --fix src/... -c /tmp/lint/.golangci.yml]
--Error detail:
level=error msg="[linters_context] typechecking error: pattern ./src/...: directory prefix src does not contain main module or its selected dependencies"
```



We're assuming it's because the `go.mod` and `go.sum` files are in `./src` and having these files in a sub-directory isn't supported by golangci-lint: 
- <https://github.com/golangci/golangci-lint/issues/4189#issuecomment-1802689589>
- <https://github.com/golangci/golangci-lint/issues/4189#issuecomment-1803724086>

**Comment by tomkingchen** [comment]
I was trying to work around the issue by using the below megalinter config
```yaml
GO_GOLANGCI_LINT_PRE_COMMANDS:
    - cd my_src_folder
 GO_GOLANGCI_LINT_POST_COMMANDS:
    - cd ..
```
However, this causes Megalinter to error out 😢 
```
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/megalinter/run.py", line 11, in <module>
    linter = megalinter.Megalinter({"cli": True, "request_id": str(uuid.uuid1())})
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/megalinter/MegaLinter.py", line 161, in __init__
    and pre_post_factory.has_npm_or_yarn_commands(self.request_id)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/megalinter/pre_post_factory.py", line 204, in has_npm_or_yarn_commands
    or "yarn" in command_info["command"]
                 ~~~~~~~~~~~~^^^^^^^^^^^
TypeError: string indices must be integers, not 'str'
```

**Comment by nvuillam** [comment]
@tomkingchen while we don't have the exact command line which must run to handle your use case, can't help 😢
